### ISSUE TITLE
pass class data or other content format

### ISSUE THREAD

**Issue by pishguy** [pdliuw/airoute#1]
in this library how can i pass data such as map, array or class data?

**Comment by pdliuw** [comment]
Airoute.pushNamed(
                routeName: "/Page",
                argument: "argument is dynamic data type. it can be any type data",
              );

argument is dynamic data type . 
argument can be basic type and object .

Airoute(https://github.com/pdliuw/airoute) 

Why not verify it yourself?
I'm sure you will be pleasantly surprised

**Comment by pishguy** [comment]
@pdliuw i'll tested that, sure, thanks
