### ISSUE TITLE
fade effect

### ISSUE THREAD

**Issue by pishguy** [pdliuw/airoute#4]
is any solution to make fade effect for slide animation?

**Comment by pdliuw** [comment]
** 1、Default support animation:

              Airoute.pushNamedWithAnimation(
                routeName: "/routeName",
                routePageAnimation: AirouteTransition.Slide,
              );

AirouteTransition.Slide 
AirouteTransition.Fade
AirouteTransition.Rotation
AirouteTransition.Scale

** 2、Custom animation style:

              Airoute.pushNamedWithAnimation(
                routeName: "/routeName",
                routePageAnimation: (
                  BuildContext context,
                  Animation<double> animation,
                  Animation<double> secondaryAnimation,
                  Widget page,
                ) {
                  return SlideTransition(
                    position: Tween<Offset>(
                      begin: const Offset(1.0, 0.0),
                      end: const Offset(0.0, 0.0),
                    ).animate(animation),
                    child: page,
                  );
                },
              );

**Comment by pdliuw** [comment]
【next version】Thank you very much for your feedback, We will enrich the type of this animation！

**Comment by pishguy** [comment]
@pdliuw thanks. you removed `routePageAnimation` parameter from `Airoute`?

and how about `fade` effect?

my mean is slide animation with fade effect

**Comment by pishguy** [comment]
@pdliuw 

i have some problem when i try to use `Duration` in this code, some part of my code work, some others part of code doesn't work. such as using into `Drawer`. when i remove `Duration` problems resolved

```dart
Airoute.pushNamedWithAnimation(
                        routeName: "/logout",
                        duration: Duration(seconds: 800),
                        routePageAnimation: (
                            BuildContext context,
                            Animation<double> animation,
                            Animation<double> secondaryAnimation,
                            Widget page,
                            ) {
                          return FadeTransition(
                            opacity: CurvedAnimation(parent: animation, curve: Curves.easeOut),
                            child: SlideTransition(
                              position: Tween<Offset>(
                                begin: const Offset(1.0, 0.0),
                                end: const Offset(0.0, 0.0),
                              ).animate(animation),
                              child: page,
                            ),
                          );
                        },
                      );
```

**Comment by pdliuw** [comment]
solution：

replace
```
duration: Duration(seconds: 800),
```
with
```
duration: Duration(milliseconds: 800),
```

So far, this problem has been solved

**Comment by pdliuw** [comment]
Thank you very much for your help ！

I will further investigate this issue: 
```
duration: Duration(seconds: 800),
```
To enhance the robustness of this library

**Comment by pishguy** [comment]
> 
> 
> solution：
> 
> replace
> 
> ```
> duration: Duration(seconds: 800),
> ```
> 
> with
> 
> ```
> duration: Duration(milliseconds: 800),
> ```
> 
> So far, this problem has been solved

ohhhhhh!!! I'm so sorry :(
