### ISSUE TITLE
slide animation direction

### ISSUE THREAD

**Issue by pishguy** [pdliuw/airoute#5]
is any way to set optional direction for slide animation?

for example from `left to right`, `right to left`, `top to bottom` or `bottom to top`

**Comment by pdliuw** [comment]
** 1、Default support animation:

              Airoute.pushNamedWithAnimation(
                routeName: "/routeName",
                routePageAnimation: AirouteTransition.Slide,
              );

AirouteTransition.Slide 
AirouteTransition.Fade
AirouteTransition.Rotation
AirouteTransition.Scale

** 2、Custom animation style:

              Airoute.pushNamedWithAnimation(
                routeName: "/routeName",
                routePageAnimation: (
                  BuildContext context,
                  Animation<double> animation,
                  Animation<double> secondaryAnimation,
                  Widget page,
                ) {
                  return SlideTransition(
                    position: Tween<Offset>(
                      begin: const Offset(1.0, 0.0),
                      end: const Offset(0.0, 0.0),
                    ).animate(animation),
                    child: page,
                  );
                },
              );

**Comment by pdliuw** [comment]
【next version】Thank you very much for your feedback, We will enrich the type of this animation！

**Comment by pishguy** [comment]
how can i use fade animation to push routes instead of slider?

**Comment by pdliuw** [comment]
> how can i use fade animation to push routes instead of slider?

                Airoute.pushNamedWithAnimation(
                  routeName: "/SecondPage",
                  argument: "$_content \n happy to see you",
                  routePageAnimation: AirouteTransition.Fade,
                );

AirouteTransition:

    AirouteTransition.Fade,
    AirouteTransition.Slide,
    AirouteTransition.Scale,
    AirouteTransition.Rotation,
