### ISSUE TITLE
Error: 'ActionFactory' isn't a type.     Map<LocalKey, ActionFactory> actions

### ISSUE THREAD

**Issue by pishguy** [pdliuw/airoute#9]
/F:/software/flutter/.pub-cache/hosted/pub.dartlang.org/airoute-0.3.2/lib/route/app.dart:162:19: Error: 'ActionFactory' isn't a type.
    Map<LocalKey, ActionFactory> actions,
                  ^^^^^^^^^^^^^

**Comment by philos3** [comment]
![image](https://user-images.githubusercontent.com/8424317/92676785-e1d73000-f354-11ea-864e-f9590f16f6b9.png)
这个问题修复了吗？

**Comment by pdliuw** [comment]
Yes,it's okay
1、please upgrade flutter = v1.20 stable, and use airoute = v0.3.5 , it's okay
